name: Automated Code Review

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '**.vue'
      - '**.js'
      - '**.ts'

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r code-review-ai/requirements.txt

      - name: Get changed files
        id: changed-files
        run: |
          echo "files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -E '\.vue$|\.js$|\.ts$' | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Run code review
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for file in ${{ steps.changed-files.outputs.files }}; do
            echo "Reviewing $file..."
            python code-review-ai/src/code_reviewer.py "$file" >> review.txt
          done

      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const review = fs.readFileSync('review.txt', 'utf8');
            const body = `## 🤖 Automated Code Review

            ${review}

            ---
            *This review was automatically generated by Claude 3.5 Sonnet*`;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: body
            });
